[theme]

# Primary accent for interactive elements
primaryColor = "#154C79"

# Background color for the main content area
backgroundColor = "#F8F8FF"

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = "#FFFFFF"

# Color used for almost all text
textColor = "#000000"

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"
